    name: Blog Deployment
    on: 
        push:
            branches: 
                - master

    jobs:
        build: 
            runs-on: ubuntu-latest
            name: Checkout, Install, Build
            steps:
                - name: Checkout branche
                  uses: actions/checkout@master

                - name: Use Node.js
                  uses: actions/setup-node@master
                  with:
                    node-version: 16.x

                - name: Cache node modules
                  uses: actions/cache@v2
                  id: cache
                  with:
                    path: node_modules
                    key: npm-packages-${{ hashFiles('**/package-lock.json') }}

                - name: Install Dependencies
                  if: steps.cache.outputs.cache-hit != 'true'
                  run: npm Install

                - name: Build
                  run: npm run build
                    
                - name: copy Cname
                  run: cp CNAME public/ 

                - name: Deploy changes
                  uses: maxheld83/ghpages@v0.2.1
                  env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    # API_KEY 에는 자신이 secret을 생성할 때 설정한 이름으로 넣어야 한다
                    GH_PAT: ${{ secrets.BLOG_SECRET_KEY }}
                    BUILD_DIR: 'public/'
                #  uses: peaceiris/actions-gh-pages@v3
                #  with:
                #    github_token: ${{ secrets.GITHUB_TOKEN }}
                #    publish_dir: ./public
