name: Blog Deployment
on: 
    push:
        branches: 
            - master

jobs:
    deploy: 
        runs-on: ubuntu-latest
        name: Checkout, Install, Build
        steps:
            - name: Checkout branche
              uses: actions/checkout@master
            
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 16.x
                cache: 'npm'

            - name: Install Node.js
              run: npm install -g gatsby-cli
              
            - name: Build
              run: npm run deploy
                
            - name: copy Cname
              run: cp CNAME public/ 

            - name: Deploy changes
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public
                publish_branch: gh-pages